### ISSUE TITLE
Guide - 10 Minute Introduction

### ISSUE THREAD

**Issue by bebraw** [webpack/webpack.io#29]
[Stub](https://github.com/webpack/webpack.io/blob/master/src/content/10-minute-introduction.md).

Feel free to comment here if you have ideas on what this guide should cover. Link to potential resources too.

**Comment by logaretm** [comment]
Maybe it should cover:
* What is Webpack? (in a small paragraph)
* Establishing Mindset (JavaScript file as entry point) or how it works at its highest levels, some colleagues had issues understanding how it works since they were using gulp.
* Files and Loaders (in two or three lines).

Then move on to a small example:
* Installation.
* Basic html page with an entry point, that just logs something or manipulates an element using jQuery.
* Bundling the JS files.
* Extracting chunks (like vendor) with CommonsChunk plugin.
* Adding CSS (css loader and style loader).
* Adding static resources like an image (file/url loader).
* Optimization (Uglify, Clean).
* HMR.

probably that would be somewhat enough to get used to most of Webpack concepts at a high level. I'm not sure if its too short or a bit long.

Probably some short version of [this post](https://blog.madewithlove.be/post/webpack-your-bags/).

**Comment by bebraw** [comment]
Good ideas. We can likely defer some of those `Then move on to a small example:` bits to specific "how tos" assuming we follow that kind of structure. It's more than ten minutes of effort then, but that doesn't hurt.

The main goal of this article is to help the user to go from level zero to level one after all and even guide to the documentation so the person knows how to use it effectively.

We can link to external "getting started" guides at the end.

**Comment by bebraw** [comment]
I'm merging this with #15. We need just one good intro to the topic. The rest of the documentation supports that. I'll move your synopsis there so we don't lose it.
