### ISSUE TITLE
Infrastructure - windows support

### ISSUE THREAD

**Issue by sokra** [webpack/webpack.io#30]
Please make sure that I can build this project too.

* no linux tool in npm script
* `path.join` instead of `a/b`

**Comment by gregvenech** [comment]
The `sudo` was in the npm scripts was a hack on my part because of something I misconfigured in the dev-config. Luckily @bebraw [took care of that][1]. 

I think [this commit][2] will fix the windows' issue, if not feel free to push whatever I missed.

[1]: https://github.com/webpack/webpack.io/commit/aa40c8b809d879549b2292b4afdde4f4ac40a630
[2]: https://github.com/webpack/webpack.io/commit/700915c09b9c42e0867b0f3d566d4df6dfdc9c8b

**Comment by gregvenech** [comment]
Closing this for now as I think it's fixed, I don't have a windows box to test on so if anyone is still having issues please comment with the error and we'll reopen it.
